import pandas as pd
import glob
import os

print("=== DEEP COMPARISON OF DRAFT VS RUN3 DATA ===")

tables_dir = 'Run3/tables'

# Load tables
cov = pd.read_csv(os.path.join(tables_dir, '01_experiment_coverage.csv'))
summary = pd.read_csv(os.path.join(tables_dir, '02_model_dataset_summary.csv'))
prompt_struct = pd.read_csv(os.path.join(tables_dir, '03_prompt_structure_results.csv'))
example_count = pd.read_csv(os.path.join(tables_dir, '04_example_count_results.csv'))
selection = pd.read_csv(os.path.join(tables_dir, '05_example_selection_results.csv'))
ordering = pd.read_csv(os.path.join(tables_dir, '06_example_ordering_results.csv'))
model_comp = pd.read_csv(os.path.join(tables_dir, '07_model_comparison.csv'))
efficiency = pd.read_csv(os.path.join(tables_dir, '09_efficiency_results.csv'))
reliability = pd.read_csv(os.path.join(tables_dir, '10_reliability_results.csv'))
stats = pd.read_csv('Run3/analysis/statistical_analysis.csv')

print("\n--- 1. COVERAGE & RUN STATS ---")
print("Coverage Table:")
print(cov[['Dataset', 'Model', 'Actual Total Runs', 'Completed Runs', 'Failed Runs']])
print("Draft Claim: 100 total runs, 92 completed, 8 failed. 66 attributable, 34 unlinked.")
print(f"Run3 Actual: Total Runs = {cov['Actual Total Runs'].sum()}, Completed = {cov['Completed Runs'].sum()}, Failed = {cov['Failed Runs'].sum()}")
print("Run3 Attributable: ALL 100 runs are linked to their models/datasets!")
print("  - Rotten Tomatoes (Gemma 2 2B): 36 runs (34 complete, 2 failed)")
print("  - Rotten Tomatoes (Qwen 2.5 3B): 42 runs (38 complete, 4 failed)")
print("  - DBPedia 14 (DeepSeek R1 1.5B): 22 runs (20 complete, 2 failed)")
print("  - BoolQ: 0 runs executed")

print("\n--- 2. PROMPT STRUCTURE RESULTS ---")
print(prompt_struct)
print("\nDraft Claims for Prompt Structure:")
print("  - Rotten Tomatoes Qwen 2.5 3B: Instruction=0.3722, Example-Based=0.4097, Mixed=0.3125")
print("  - Rotten Tomatoes Gemma 2 2B: 0.0000 for all 3 structures!")
print("  - DBPedia DeepSeek R1 1.5B: Mixed = 0.1000 Acc")
print("\nRun3 Actual for Prompt Structure:")
print("  - Rotten Tomatoes Qwen 2.5 3B: Example-Based=0.0, Instruction=0.0, Mixed=0.0167 (Acc)")
print("  - Rotten Tomatoes Gemma 2 2B: Example-Based=0.0750, Instruction=0.3750, Mixed=0.1167 (Acc)")
print("  - DBPedia DeepSeek R1 1.5B: Mixed = 0.3847 Acc (F1=0.2668, Latency=3348.2ms)")

print("\n--- 3. EXAMPLE COUNT RESULTS ---")
print(example_count)
print("\nDraft Claims for Example Count:")
print("  - DeepSeek DBPedia: 0-shot=0.1500, 1-shot=0.4444, 3-shot=0.4444, 5-shot=0.3889")
print("  - Qwen Rotten Tomatoes: 0.0000 across all counts")
print("  - Gemma Rotten Tomatoes: 0-, 1-, 3-shot=0.0000, 5-shot=0.5000")
print("\nRun3 Actual for Example Count:")
print("  - DeepSeek DBPedia: 0-shot=0.0625, 1-shot=0.4107, 3-shot=0.3847, 5-shot=0.3500")
print("  - Qwen Rotten Tomatoes: 0-shot=0.0, 1-shot=0.0, 3-shot=0.0167, 5-shot=0.0")
print("  - Gemma Rotten Tomatoes: 0-shot=0.4000, 1-shot=0.4333, 3-shot=0.1167, 5-shot=0.2000")

print("\n--- 4. EXAMPLE SELECTION RESULTS ---")
print(selection)
print("\nDraft Claims for Selection:")
print("  - DeepSeek DBPedia: Random=0.0625, Balanced=0.4107, Sequential=Failed")
print("  - Qwen Rotten Tomatoes: Random=0.0, Balanced=0.0, Sequential=Failed")
print("  - Gemma Rotten Tomatoes: Random=0.0, Balanced=0.1000")
print("\nRun3 Actual for Selection:")
print("  - DeepSeek DBPedia: Random=0.3847 (8 runs), Balanced=0.2111 (2 runs), Sequential=Failed (2 runs)")
print("  - Qwen Rotten Tomatoes: Random=0.0167 (12 runs), Balanced=0.0 (4 runs), Sequential=0.1000 (2 complete / 2 failed)")
print("  - Gemma Rotten Tomatoes: Random=0.1167 (10 complete / 2 failed), Balanced=0.1500 (4 runs)")

print("\n--- 5. EXAMPLE ORDERING RESULTS ---")
print(ordering)
print("\nDraft Claims for Ordering:")
print("  - DeepSeek DBPedia: Original=0.3500, Random=0.3889, Similarity=0.2111")
print("  - Qwen Rotten Tomatoes: Original=0.0, Random=0.0, Similarity=0.0")
print("  - Gemma Rotten Tomatoes: No completed ordering configurations")
print("\nRun3 Actual for Ordering:")
print("  - DeepSeek DBPedia: Original=0.3847 (8 runs), Random=0.4097 (2 runs), Similarity=0.3125 (2 runs)")
print("  - Qwen Rotten Tomatoes: Original=0.0167 (12 runs), Random=0.0500 (4 runs), Similarity=0.2500 (4 runs)")
print("  - Gemma Rotten Tomatoes: Original=0.1167 (10 runs)")

print("\n--- 6. STATISTICAL ANALYSIS & REFERENCES ---")
print(stats)
print("\nDraft Claims:")
print("  - 'No significance test was performed'")
print("\nRun3 Actual:")
print("  - One-way ANOVA WAS performed!")
print("  - Model Family Effect: F = 19.28, p = 1.11e-07 (Statistically Significant)")
print("  - Dataset Task Effect: F = 16.31, p = 0.00011 (Statistically Significant)")
print("  - Prompt Structure Effect: F = 1.36, p = 0.268 (Not Significant)")
print("  - Example Count Effect: F = 1.60, p = 0.201 (Not Significant)")
print("  - Example Ordering Effect: F = 1.07, p = 0.354 (Not Significant)")
